# Generated by Django 3.2.25 on 2024-09-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('maintext', models.TextField()),
                ('subtext', models.TextField()),
                ('schedule', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
    ]
